name: Docker Hub Image Deploy

on:
  push:
    branches: ["main", "develop"]

jobs:
  docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Extract SERVER_VERSION from launch.sh
        id: extract-version
        run: |
          SERVER_VERSION=$(grep 'VERSION_TAG=' launch.sh | cut -d '=' -f2)
          echo "SERVER_VERSION=$SERVER_VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push the Docker image (versioned tag)
        uses: docker/build-push-action@v5.3.0
        with:
           context: .
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/oceanblock2:${{ env.SERVER_VERSION }}

      - name: Build and push the Docker image (latest tag)
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5.3.0
        with:
           context: .
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/oceanblock2:latest

